defmodule Backend.Repo.Migrations.CreateInitialSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :hashed_password, :text, null: false
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :phone, :text
      add :role, :text, default: "user"
      add :is_active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id, :uuid
    end

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:time_entries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :description, :text
      add :hours, :decimal, null: false
      add :date, :date, null: false
      add :hourly_rate, :decimal
      add :is_billable, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id, :uuid, null: false
      add :ticket_id, :uuid
      add :user_id, :uuid, null: false
    end

    create table(:tickets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :state, :text, null: false, default: "open"
      add :priority, :text, default: "medium"
      add :category, :text, default: "task"
      add :review_notes, :text
      add :resolved_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id, :uuid, null: false
      add :reporter_id, :uuid
      add :assignee_id, :uuid
    end

    create table(:projects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:time_entries) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "time_entries_project_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :ticket_id,
             references(:tickets,
               column: :id,
               name: "time_entries_ticket_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :user_id,
             references(:users,
               column: :id,
               name: "time_entries_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tickets) do
      modify :project_id,
             references(:projects,
               column: :id,
               name: "tickets_project_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :reporter_id,
             references(:users,
               column: :id,
               name: "tickets_reporter_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :assignee_id,
             references(:users,
               column: :id,
               name: "tickets_assignee_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:projects) do
      add :name, :text, null: false
      add :description, :text
      add :state, :text, null: false, default: "draft"
      add :budget, :decimal
      add :spent, :decimal, default: "0"
      add :start_date, :date
      add :target_end_date, :date
      add :actual_end_date, :utc_datetime
      add :approved_at, :utc_datetime
      add :rejection_reason, :text
      add :cancellation_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id, :uuid, null: false
    end

    create table(:invitations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :citext, null: false
      add :token, :text, null: false
      add :role, :text, default: "user"
      add :expires_at, :utc_datetime, null: false
      add :accepted_at, :utc_datetime
      add :cancelled_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :company_id, :uuid, null: false
      add :invited_by_id, :uuid, null: false
      add :accepted_by_id, :uuid
    end

    create table(:documents, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :file_path, :text, null: false
      add :file_size, :bigint
      add :mime_type, :text
      add :category, :text, default: "other"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :project_id,
          references(:projects,
            column: :id,
            name: "documents_project_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :uploaded_by_id,
          references(:users,
            column: :id,
            name: "documents_uploaded_by_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:companies, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:users) do
      modify :company_id,
             references(:companies,
               column: :id,
               name: "users_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:projects) do
      modify :company_id,
             references(:companies,
               column: :id,
               name: "projects_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:invitations) do
      modify :company_id,
             references(:companies,
               column: :id,
               name: "invitations_company_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :invited_by_id,
             references(:users,
               column: :id,
               name: "invitations_invited_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :accepted_by_id,
             references(:users,
               column: :id,
               name: "invitations_accepted_by_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:invitations, [:email, :company_id],
             name: "invitations_unique_pending_email_company_index",
             where: "(accepted_at IS NULL AND cancelled_at IS NULL)"
           )

    alter table(:companies) do
      add :name, :text, null: false
      add :org_number, :text, null: false
      add :address, :text
      add :city, :text
      add :postal_code, :text
      add :country, :text, default: "Sweden"
      add :phone, :text
      add :website, :text
      add :is_active, :boolean, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:companies, [:org_number], name: "companies_unique_org_number_index")

    create table(:comments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :body, :text, null: false
      add :is_internal, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :ticket_id,
          references(:tickets,
            column: :id,
            name: "comments_ticket_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :author_id,
          references(:users,
            column: :id,
            name: "comments_author_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:comments, "comments_ticket_id_fkey")

    drop constraint(:comments, "comments_author_id_fkey")

    drop table(:comments)

    drop_if_exists unique_index(:companies, [:org_number],
                     name: "companies_unique_org_number_index"
                   )

    alter table(:companies) do
      remove :updated_at
      remove :inserted_at
      remove :is_active
      remove :website
      remove :phone
      remove :country
      remove :postal_code
      remove :city
      remove :address
      remove :org_number
      remove :name
    end

    drop_if_exists unique_index(:invitations, [:email, :company_id],
                     name: "invitations_unique_pending_email_company_index"
                   )

    drop constraint(:invitations, "invitations_company_id_fkey")

    drop constraint(:invitations, "invitations_invited_by_id_fkey")

    drop constraint(:invitations, "invitations_accepted_by_id_fkey")

    alter table(:invitations) do
      modify :accepted_by_id, :uuid
      modify :invited_by_id, :uuid
      modify :company_id, :uuid
    end

    drop constraint(:projects, "projects_company_id_fkey")

    alter table(:projects) do
      modify :company_id, :uuid
    end

    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    drop constraint(:users, "users_company_id_fkey")

    alter table(:users) do
      modify :company_id, :uuid
    end

    drop table(:companies)

    drop constraint(:documents, "documents_project_id_fkey")

    drop constraint(:documents, "documents_uploaded_by_id_fkey")

    drop table(:documents)

    drop table(:invitations)

    alter table(:projects) do
      remove :company_id
      remove :updated_at
      remove :inserted_at
      remove :cancellation_reason
      remove :rejection_reason
      remove :approved_at
      remove :actual_end_date
      remove :target_end_date
      remove :start_date
      remove :spent
      remove :budget
      remove :state
      remove :description
      remove :name
    end

    drop constraint(:tickets, "tickets_project_id_fkey")

    drop constraint(:tickets, "tickets_reporter_id_fkey")

    drop constraint(:tickets, "tickets_assignee_id_fkey")

    alter table(:tickets) do
      modify :assignee_id, :uuid
      modify :reporter_id, :uuid
      modify :project_id, :uuid
    end

    drop constraint(:time_entries, "time_entries_project_id_fkey")

    drop constraint(:time_entries, "time_entries_ticket_id_fkey")

    drop constraint(:time_entries, "time_entries_user_id_fkey")

    alter table(:time_entries) do
      modify :user_id, :uuid
      modify :ticket_id, :uuid
      modify :project_id, :uuid
    end

    drop table(:projects)

    drop table(:tickets)

    drop table(:time_entries)

    drop table(:tokens)

    drop table(:users)
  end
end
